
- name: Install yum
  yum:
    name:
      - wget
      - java-1.8.0-openjdk

- name: Download jenkins.repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
- name: Ensure Jenkins is Installed
  yum :
    name: jenkins
    update_cache: yes
    state: present


- name: Change Jenkins Java options
  lineinfile: 
    dest=/etc/sysconfig/jenkins
    regex=^JENKINS_JAVA_OPTIONS= 
    line=JENKINS_JAVA_OPTIONS="{{jenkins.JAVA_OPTIONS}}"
  become: true

- name: Start Jenkins server and enable it
  systemd: name=jenkins state=restarted enabled=yes
  become: yes

